name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: rajchaudhari/cicd-test
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
